# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/*schema.rb'
    - 'db/seeds.rb'
    - 'doc/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'workspace/**/*'
    - 'test/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

# The project has a soft limit of 80 chars for line length, but up to 100 chars
# are allowed in some cases.
Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true

# Methods should be short. But sometimes it is not possible.
Metrics/MethodLength:
  Max: 20

# Do not enforce documentation for all class definitions
Documentation:
  Enabled: false

# Ignore "Missing frozen string literal comment."
Style/FrozenStringLiteralComment:
  Enabled: false

# Method definitions after `private` or `protected` isolated calls need one extra level of indentation.
Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails
